### ISSUE TITLE
Spaces in tags are removed

### ISSUE THREAD

**Issue by scottmartincampbell** [windingwind/zotero-tag#22]
Great looking add on, but when I tried to use the tag "to review" to the rule "add on item add", the space is stripped when I save the rule, which become "toreview". 

It looks like this is because of the regex around line 22 in preferences.js:
 
```
rule.tags = document
    .getElementById("zoterotag-rules-#-tags")
    .value.replace(/\s/g, "")
    .split(",");
```

As far as I know, a valid Zotero tag can have a space, but zotero-tag strips them, eliminating my use case. Is there a reason for the regex? A work around? Thanks!

**Comment by windingwind** [comment]
@scottmartincampbell 
Fixed in v0.2.6

**Comment by scottmartincampbell** [comment]
Thanks for the quick response! 

But, I hate to say this: I did a few tests with v0.2.6 and it's still happening, with spaces stripped.

It looks like there's another regex in refreshRule around line 47 in preferences.js: 

```
 rule.tags = document
    .getElementById(`zoterotag-rules-${id}-tags`)
    .value.replace(/\s/g, "")
    .split(",");
```

Which is called by the Add/Refresh button at line 206, so it's stripping spaces there too. Hopefully you can fix and re-release. Sorry!

**Comment by windingwind** [comment]
Fixed! Thanks. I forgot the test in the last release
Feel free to give suggestions/report bugs!
